### ISSUE TITLE
Some recipe sources fail to parse

### ISSUE THREAD

**Issue by gryphonmyers** [flauschtrud/broccoli#183]
First of all, I love this app! I saw it appear in f-droid and it is exactly what I want to manage recipes.

When I was importing some of my recipes, I noticed a few sources for which I get a "cannot be read" error when I attempt to import. I am guessing these websites have strange / unexpected dom structure. Here are the ones I found:

- https://www.allrecipes.com/recipe/147103/delicious-egg-salad-for-sandwiches/
- https://www.foodandwine.com/recipes/caramelized-broccoli-garlic
- https://www.loveandlemons.com/vegan-carrot-cake/
- https://www.seriouseats.com/detroit-style-pizza-recipe

**Comment by flauschtrud** [comment]
Thanks a lot for your feedback :)

I just had a look: the first, second and fourth link all seem to be the same problem, so I created an issue specifically for this bug:  #189 Thanks for reporting, I hadn't encountered any sites yet, that had this problem.

The recipe in the third link provides some metadata in JSON but unfortunately not the content of the recipe so I can't do anything about it. Many blogs and sites provide the metadata in JSON, because it helps with search engine optimization, but I assume some choose not to do so because they don't want external sites and tools to read their content.

I'll close this issue, but feel free to create another one if you encounter any more sites that do not work :)

**Comment by gryphonmyers** [comment]
> Thanks a lot for your feedback :)
> 
> I just had a look: the first, second and fourth link all seem to be the same problem, so I created an issue specifically for this bug:  #189 Thanks for reporting, I hadn't encountered any sites yet, that had this problem.
> 
> The recipe in the third link provides some metadata in JSON but unfortunately not the content of the recipe so I can't do anything about it. Many blogs and sites provide the metadata in JSON, because it helps with search engine optimization, but I assume some choose not to do so because they don't want external sites and tools to read their content.
> 
> I'll close this issue, but feel free to create another one if you encounter any more sites that do not work :)

Ah that makes sense. In the case of the third link, I suppose an error message is reasonable, but perhaps it could provide a more descriptive error? Like "link does not include required metadata"?

**Comment by flauschtrud** [comment]
> Ah that makes sense. In the case of the third link, I suppose an error message is reasonable, but perhaps it could provide a more descriptive error? Like "link does not include required metadata"?

Hmm, I deliberately chose to not use any technical terms in the error message, because I assume that makes more sense for the general user. It's always hard to tell what's best if you are a tech person yourself :D

**Comment by gryphonmyers** [comment]
> 

Heh, that's fair. I'm also a tech person so maybe my opinion is worthless

**Comment by flauschtrud** [comment]
> Heh, that's fair. I'm also a tech person so maybe my opinion is worthless

It's for sure not worthless ;)
