### ISSUE TITLE
Subcategories and courses

### ISSUE THREAD

**Issue by OrsonDeWitt** [flauschtrud/broccoli#226]
Thanks for the great app! I love it, but I have a few suggestions that would greatly improve usability.
1. Add "courses" - similar to the category field, let the user add their own courses, and show them in the left-hand side hamburger menu (either as a drop-down of "Recipes" or just a list inside the menu). This will help a lot to organize when you have hundreds of recipes. Why not use categories, you may ask? Because a) they are already taken by categories themselves, b) this would allow you to filter by the course AND category. So you don't get breakfast suggestions when you are searching for recipes with eggs.
![courses](https://github.com/flauschtrud/broccoli/assets/26813733/6b598406-4faf-473d-9b56-41d0e3310cd4)

2. Add "cold"/"hot" dish toggle. There are many foods that you (or I) don't eat when it's hot outside (soups, spicy dishes) or when it's cold (summer salads), so having a toggle would help immensely to choose foods without having to waste time scrolling.
![hot](https://github.com/flauschtrud/broccoli/assets/26813733/f8be8e23-43ed-4597-9157-7aad0fae2108)
![cold](https://github.com/flauschtrud/broccoli/assets/26813733/980af7ae-554b-4bad-bf8d-ce2a42aba2b2)

And the in-recipe toggle to make a dish hot or cold:
![hums](https://github.com/flauschtrud/broccoli/assets/26813733/7bcc6191-72ef-40d2-9214-91ef1779df26)

Thanks!

**Comment by flauschtrud** [comment]
I would suggest you try out hashtags to meet your needs, they are super flexible.

You could add something like "#breakfast #hot" or "#snacks #cold" to the description of your recipes (or whatever other hashtag that might be of interest for you). You can then search for specific hashtags (even within a category) and they are linked in the recipe descriptions. You could even search for something like "#breakfast eggs".

Let me know if this works for you. I try to keep the app and the UI clean and simple, so I don't want to add toggles for all possible usecases, but I think hashtags are a great alternative, that everyone can use exactly as it suits themselves best.

But I'm curious, what are your categories? I'm asking because I set it up so that categories are courses (and I use hashtags to add more details like regional cuisines or whether a recipe is good for parties etc.). It's always interesting to learn how people use the app :)

**Comment by OrsonDeWitt** [comment]
Hashtags are more useful on keyboard, but when I'm on mobile the less clicking I have to do, the better. Having to type out #breakfast #eggs is far from peak UX for me :)
My ideal recipe book would look like this:
• Breakfast
    • Savory
        • Toast
        • Sandwich
    • Sweet
        • Oatmeal
        • Cereal
• Main
    • Potatoes
        • Mushroom Sauce
        • Carrot Sauce
    • Indian
        • Mujadara
        • Curry
    • Oven dishes
        • Quiche
        • Casserole
                • Filling X
                • Filling Y
     • Pizzas
        • Lentil Pizza
                • Topping X
                • Topping Y
        • Corn Pizza
                • Topping X
    
 And so on. And then, in summer for example, I would go on to filter out all the "hot" dishes - soups, Indian, oven dishes, etc.
 The app is severely lacking in a way to achieve this, as well as customizations/variations — right now, if I wanted to include, for example, 2 topping sets that go well with the lentil pizza, I would have to create two separate recipes that would clog it up and would make it harder to navigate through the app.
 And having lots of categories like I would is just creating an endless list that's just as hard to navigate. I can't remember all the tags for every subcategory for every variation (when I am thinking of what to cook this week), if I could do this then I would not need a recipe app :)

**Comment by flauschtrud** [comment]
I added to more specific issues regarding categories: #238 and #239 Feel free to add any more comments there if something is missing :)
