### ISSUE TITLE
F-Droid reproducible build failed

### ISSUE THREAD

**Issue by linsui** [flauschtrud/broccoli#250]
https://gitlab.com/fdroid/fdroiddata/-/jobs/7252061841 The content of the apk is identical but the apk is different. Is there anything changed?

**Comment by flauschtrud** [comment]
What do you mean exactly by identical but different?

This is the changelog for the f-droid Release: https://github.com/flauschtrud/broccoli/compare/v1.2.10-fdroid...v1.2.11-fdroid 

The majority of changes concerns translations. There are some small bug fixes, but I also updated all dependencies including Gradle: 

- https://github.com/flauschtrud/broccoli/commit/1b26ed50a1dc6a98f1e8385bcb454707fa2d26d2
- https://github.com/flauschtrud/broccoli/commit/2cab62aabe632ed5013e542901d074c8cb2f11f4

Might there be any known issues regarding this Gradle version? I'm wondering because I remember that there have been some Gradle-specific issues when I first setup the app for deployment on f-droid.

**Comment by licaon-kter** [comment]
We're narrowed it down to: https://gitlab.com/fdroid/fdroiddata/-/issues/3299

**Comment by licaon-kter** [comment]
@flauschtrud or don't use 34, keep it like that, but make it do `apksigner sign --alignment-preserved true  ...`

**Comment by licaon-kter** [comment]
Based on the docs here: https://github.com/obfusk/apksigcopier#what-about-signatures-made-by-apksigner-from-build-tools--3500-rc1

I've updated the recipe: https://gitlab.com/fdroid/fdroiddata/-/commit/1d7967b75bcde8c716206b803cb404a8b4833f30

feel free to star the Google issue https://issuetracker.google.com/issues/351408623

/close this

**Comment by flauschtrud** [comment]
@linsui @licaon-kter 
Sorry for getting back so late and thanks a lot for your investigations!
